version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elknetwork
  kibana:
    image: kibana:7.9.2
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork

  actuator1:
    image: actuator
    environment:
      - MANAGEMENT_METRICS_TAGS_APPLICATION=actuator1
      - MANAGEMENT_METRICS_EXPORT_ELASTIC_HOST=http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
    ports:
      - 8181:8080
    networks:
      - elknetwork

  actuator2:
    image: actuator
    environment:
      - MANAGEMENT_METRICS_TAGS_APPLICATION=actuator2
      - MANAGEMENT_METRICS_EXPORT_ELASTIC_HOST=http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
    ports:
      - 8182:8080
    networks:
      - elknetwork

networks:
  elknetwork:
    driver: bridge